### ISSUE TITLE
[UI개선] front-end 단에서 form 검증 로직 추가

### ISSUE THREAD

**Issue by jongpak** [jongpak/prob-board#26]
항상 게시물 수정에서 비밀번호를 다시 입력하는 것을 빼먹고 submit을 하다보니 글을 날리는 경우가 많다. (물론 크롬이 잘 해줘서 뒤로가기 눌러도 글 내용이 살아있지만 ^^)

암튼, 개발버전이라고 너무 front-end 에 소홀히하고 있는데.. 자바스크립트 정도로 검증은 해줘야 사용자 관점에서 좋을 듯 하다 (아니 당연히 해야지..)

**Comment by jongpak** [comment]
HTML5의 ```required``` 와 ```type="email"``` 속성을 이용하여 해결하자

**Comment by catgarret** [comment]
다음 Article 참고할 것
[https://css-tricks.com/almanac/selectors/r/required/](https://css-tricks.com/almanac/selectors/r/required/)

**Comment by jongpak** [comment]
ㅠㅠ 덮어씌어져 다시 오픈..ㅠ

**Comment by jongpak** [comment]
적용 완료
https://github.com/jongpak/prob-board/pull/61
