### ISSUE TITLE
[UI개선] 다양한 임시 필드 생성 기능

### ISSUE THREAD

**Issue by catgarret** [jongpak/prob-board#30]
임의로 다양한 입력필드 생성기능 요구.
(예_ 포트폴리오 항목: 프로젝트 기간, 사용기술, 링크, 기타 등등)

**Comment by jongpak** [comment]
이거는 아예 프로젝트 컨셉 자체를 바꿔야겠다.
prob-cms (가칭)로 프로젝트를 전향하고 현재 prob-board는 그 CMS의 하위로 들어가는데 좋을 것 같음.
지금은 board 지만 최종 목표는 cms 등 다양한 걸 할수 있는 컨셉을 생각중..
