### ISSUE TITLE
[기능요청] 게시물 개별로 검색엔진 차단기능

### ISSUE THREAD

**Issue by catgarret** [jongpak/prob-board#36]
게시물 작성시, 검색엔진 허용안함 체크하면 해당 게시물은 검색엔진에 노출되지 않음.

**Comment by jongpak** [comment]
해당 기능은 Event 핸들러를 추가하여 검색봇일 경우 403 forbidden 등을 보여주는 방식으로 구현하면 될 것 같음. 추가 테이블이 필요함. (post_bot_crawler 테이블 등으로 posts와 외래키 걸어서 확장하면 될듯.)

**Comment by jongpak** [comment]
검색엔진을 차단하려면 비밀글 기능을 사용하는 걸로... (웹의 취지 상 정보는 open 되어야한다고 생각하기에..

**Comment by catgarret** [comment]
차라리, 중요정보 입력시 간단한 tost popup으로 유출가능성 있다고 알려주는 편이 나을것 같음.
(ex_ 주민번호, 이메일, 휴대폰번호, 주소 등등...)
ᐧ

이동규 드림.

*이동규* Lee Dong-Kyu

*- Mobile *+82)10-2643-9696
*- Email *official@guleum.me <jonghun.park@navercorp.com>
*- Portfolio *guleum.me <jonghun.park@navercorp.com>
*- LinkedIn *linkedin.com/in/guleum <jonghun.park@navercorp.com>
*- Behance *behance.net/guleum <jonghun.park@navercorp.com>

2017-03-16 1:47 GMT+09:00 Park Jong-Hun (JongPak) <notifications@github.com>
:

**Comment by catgarret** [comment]
특히, 호스팅쪽에 적용한다 하면
계정정보를 비밀글 체크 없이 올릴 수도 있으므로 기술적 난이도를 떠나서 필히 고려해야 할 사항임.
ᐧ

이동규 드림.

*이동규* Lee Dong-Kyu

*- Mobile *+82)10-2643-9696
*- Email *official@guleum.me <jonghun.park@navercorp.com>
*- Portfolio *guleum.me <jonghun.park@navercorp.com>
*- LinkedIn *linkedin.com/in/guleum <jonghun.park@navercorp.com>
*- Behance *behance.net/guleum <jonghun.park@navercorp.com>

2017년 3월 16일 오전 2:36, 이동규 <official@guleum.me>님이 작성:
