### ISSUE TITLE
게시물/댓글 수정시, 비밀번호 입력화면 별도로 띄어야 함.

### ISSUE THREAD

**Issue by catgarret** [jongpak/prob-board#53]
추후  비밀글, 게시물 접근권한등이 생기면 문제 생길 가능성 있음.

**Comment by jongpak** [comment]
@catgarret 일단, 수정 전에 비밀번호 한번 더 물어보도록 해놨는데, 아래와 같은 문제가 있음 UX적으로 어떤가 피드백 해줘.

1. 글수정 버튼을 누른다.
2. 비밀번호 입력화면으로 이동한다.
3. 비밀번호가 맞으면 글수정 페이지로 이동한다.
4. 글수정  페이지에서 기존에 있던 비밀번호 입력란에 비밀번호를 한번더 입력해아한다.

여기서 문제가 4번이야.
기존에 비밀번호 입력하는 것을 글수정 화면에서 **같이** 물어봤잖아? 그런데 지금은 글수정 화면이 나오기 전에 비밀번호를 물어보도록 단계를 하나 더 추가한건데, **글수정 화면의 비밀번호 입력란**이 아직 그대로 있기 때문에 비밀번호를 또 입력을 해야돼.

그러면 글 수정화면에 있던 기존 비밀번호 입력창 없애버리면 되잖아? 라고 말한텐데, 그게 조금 까다로워. 과연 글수정화면 전에 비번인증 통과 여부를 어딘가 저장해놔야하는데 이걸 쿠키에다가 저장하면 보안문제가 되고 그렇다고 hidden input에 박아넣으면 더더욱 보안문제가 생기고.. (비밀번호의 해시된 값을 넣는다고 해도 잠재적 보안 문제고..) 그러면 세션에 넣어야하나?

현실적인 대안은 다음의 두가지가 있을 것 같아.
1. 비밀번호를 수정 전, 수정화면에서 두번 입력하게 한다. (현재 방법)
2. 비밀번호를 두번 입력 하는 것이 UX 적으로 좋지 않다면 세션에 넣어서 저장을 한다.

@catgarret UX 적인 관점에서 피드백 좀 ㅇㅇ
일단 내가 방법은....귀찮으니 그냥 두번 입력하는게..ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by catgarret** [comment]
비밀번호를 두번입력하게 하는 것은,
최종적으로 작성한 긇을 다시한번 확인하게 하는 효과도 있을것 같음.
(예: Gmail 메일보내기 후 15~30초 내에 취소할 수 있는 기능 처럼.)

허나 일반사용자의 경우 귀찮으므로, 세션에 저장해서 한번만 물어보게 해야할듯.

**Comment by jongpak** [comment]
흠..일단 두번입력하는걸로 냅두다가 정 불편하면 바꿔야겠다

**Comment by jongpak** [comment]
이거 코드 수정해서 마크다운 에디터랑 충돌나는 부분있어 구조개선함

**Comment by jongpak** [comment]
비밀번호 두번 입력하는 건..일단 냅두고 이슈 종결하는 걸로..
